#!/usr/bin/env python
import tempfile, os, subprocess

if not 'DO_API_TOKEN' in os.environ:
    print("DigitalOcean API token not found. Export DO_API_TOKEN.")
    exit(1)

with tempfile.NamedTemporaryFile() as fp:
    fp.write("localhost ansible_connection=local")
    invocation = "ansible localhost -i {tmpfile} -m digital_ocean -a".format(tmpfile=fp.name).split(' ')
    invocation.append('command=ssh list_keys=true')
    subprocess.call(invocation)
